Adding optional components flag for custom script
GoogleCloudDataproc/custom-images pull request #96
Opened 2024-10-15 13:35 UTC by prince-cs

2025-01-15 06:43 UTC, IshaAg commented on custom_image_utils/shell_script_generator.py
> +    if self.args["optional_components"]:
can we add this flag just for images>=2.3

2025-01-15 06:43 UTC, IshaAg commented on startup_script/run.sh
> +    run_startup_custom_script
can we add a checksomewhere in this script to run for images>=2.3 only

2025-01-15 06:44 UTC, IshaAg commented on custom_image_utils/args_parser.py
> +_VALID_COMPONENTS = ["HIVE_WEBHCAT", "JUPYTER", "ZEPPELIN", "TRINO", "RANGER", "SOLR", "FLINK", "DOCKER", "HUDI", "ICEBERG"]
let's add PIG also here

2025-01-15 07:57 UTC, prince-cs commented on custom_image_utils/shell_script_generator.py
> +    if self.args["optional_components"]:
Adding it here is not required as I will be adding it in run.sh to execute the startup script only for 2.3 version.

2025-01-15 07:58 UTC, prince-cs commented on startup_script/run.sh
> +    run_startup_custom_script
Inside of run_startup_custom_script function, will first check for image version >= 2.3

2025-01-15 13:33 UTC, prince-cs commented on custom_image_utils/args_parser.py
> +_VALID_COMPONENTS = ["HIVE_WEBHCAT", "JUPYTER", "ZEPPELIN", "TRINO", "RANGER", "SOLR", "FLINK", "DOCKER", "HUDI", "ICEBERG"]
Done

2025-01-15 17:51 UTC, IshaAg commented on startup_script/run.sh
> +  if is_2.3 && [[ -n "$USER_DATAPROC_COMPONENTS" ]]; then
let's make is atleast 2.3

2025-01-16 07:21 UTC, prince-cs commented on startup_script/run.sh
> +  if is_2.3 && [[ -n "$USER_DATAPROC_COMPONENTS" ]]; then
Done

2025-01-21 13:39 UTC, vinayakumarb commented on custom_image_utils/args_parser.py
> +_VALID_COMPONENTS = ["HIVE_WEBHCAT", "ZEPPELIN", "TRINO", "RANGER", "SOLR", "FLINK", "DOCKER", "HUDI", "ICEBERG", "PIG"]
_VALID_OPTIONAL_COMPONENTS

2025-01-21 13:39 UTC, vinayakumarb commented on custom_image_utils/args_parser.py
> +            raise argparse.ArgumentTypeError("Invalid component selected.")
Invalid optional component <component> selected

2025-01-21 13:39 UTC, vinayakumarb commented on custom_image_utils/args_parser.py
> +    return ','.join(components)
same as `s` ?

2025-01-21 13:39 UTC, vinayakumarb commented on startup_script/run.sh
> +USER_DATAPROC_COMPONENTS=$(/usr/share/google/get_metadata_value attributes/optional-components)
why cant we combine these two lines into one statement?

2025-01-21 13:39 UTC, vinayakumarb commented on startup_script/run.sh
> +function is_version_at_least_2_3() {
Can we make this a generic function? and pass the value "2.3" ?

2025-01-21 13:39 UTC, vinayakumarb commented on startup_script/run.sh
> +  if echo "${DATAPROC_BASE_IMAGE}" | grep -q "2-3"; then
This will not support "at-least".. 
ex: "2.4" or "3.0" it will fail..

2025-01-21 17:09 UTC, prince-cs commented on startup_script/run.sh
> +function is_version_at_least_2_3() {
The problem is that here DATAPROC_IMAGE_VERSION is not present. So, I am extracting the image version from the image name itself.

2025-01-21 17:21 UTC, prince-cs commented on custom_image_utils/args_parser.py
> +_VALID_COMPONENTS = ["HIVE_WEBHCAT", "ZEPPELIN", "TRINO", "RANGER", "SOLR", "FLINK", "DOCKER", "HUDI", "ICEBERG", "PIG"]
Done

2025-01-21 17:21 UTC, prince-cs commented on custom_image_utils/args_parser.py
> +            raise argparse.ArgumentTypeError("Invalid component selected.")
Done

2025-01-21 17:24 UTC, prince-cs commented on startup_script/run.sh
> +  if echo "${DATAPROC_BASE_IMAGE}" | grep -q "2-3"; then
Can you suggest a way to get the value of image version being used.

2025-01-22 04:38 UTC, prince-cs commented on startup_script/run.sh
> +  if echo "${DATAPROC_BASE_IMAGE}" | grep -q "2-3"; then
spark version for 2.2 and 2.3 will be the same

2025-01-22 14:28 UTC, prince-cs commented on startup_script/run.sh
> +  if echo "${DATAPROC_BASE_IMAGE}" | grep -q "2-3"; then
We have dataproc_version argument by default. Passing it via metadata and storing its value in run.sh to compute the 2.3 version condition for custom startup script.

2025-02-05 16:35 UTC, IshaAg commented on startup_script/run.sh
> +    run_startup_custom_script
let's rename to "run_install_optional_components_script"

2025-02-05 16:35 UTC, IshaAg commented on startup_script/run.sh
> +    source "${BDUTIL_DIR}/startup_optional_components.sh"
rename to "install_optional_components"

2025-02-05 16:36 UTC, IshaAg commented on custom_image_utils/args_parser.py
> +      Can be a comma-separated list of components, e.g., TRINO,JUPYTER."""
let's change it from JUPYTER to some other component , as we are giving JUPYTER in the image

2025-02-06 05:04 UTC, prince-cs commented on custom_image_utils/args_parser.py
> +      Can be a comma-separated list of components, e.g., TRINO,JUPYTER."""
done

2025-02-06 05:04 UTC, prince-cs commented on startup_script/run.sh
> +    source "${BDUTIL_DIR}/startup_optional_components.sh"
done

2025-02-06 05:04 UTC, prince-cs commented on startup_script/run.sh
> +    run_startup_custom_script
done

2025-02-06 07:54 UTC, IshaAg approved these changes

2025-02-06 17:24 UTC, vinayakumarb commented on custom_image_utils/args_parser.py
> +      help="""Optional Components to be installed with the image.
I think, description can mention that, this option is applicable for images 2.3+

2025-02-06 17:26 UTC, vinayakumarb approved these changes

2025-02-06 20:07 UTC, cjac requested changes
I have yet to exercise this change, but here are a few questions I have after review.

2025-02-06 20:07 UTC, cjac commented on custom_image_utils/shell_script_generator.py
> +    if self.args["dataproc_version"]:
What happens if users specify image with with `--base-image-uri` or `--base-image-family` ?

2025-02-06 20:10 UTC, cjac commented
> _ No description provided. _

Can you please update the description to clearly state what the change will do?

2025-02-06 20:41 UTC, cjac commented on startup_script/run.sh
> +  if is_version_at_least "2.3" && [[ -n "$USER_DATAPROC_COMPONENTS" ]]; then
I think you'll want parenthesis around these conditions.

I would personally invert them and return rather than placing the entirety of the function within a conditional block.

2025-02-06 20:44 UTC, cjac commented on startup_script/run.sh
> +  if [[ $(echo "$DATAPROC_VERSION >= $VERSION" | bc -l) -eq 1 ]]; then
The variable has been named "DATAPROC_IMAGE_VERSION" for quite a while now.  And it is not set during the custom images phase, so you'll need to set the value based on environment.  

Here is my logic to select a version based on spark version:

https://github.com/GoogleCloudDataproc/initialization-actions/blob/87e2f9109b5a3ac95cabe00902aad03a0b7c0bd3/gpu/install_gpu_driver.sh#L2240

But I've been told that 2.3 will have the same spark version as 2.2, is that correct?  I see no reference to 2.3 in moma.

2025-02-06 20:50 UTC, cjac commented on startup_script/run.sh
> +  if [[ $(echo "$DATAPROC_VERSION >= $VERSION" | bc -l) -eq 1 ]]; then
also, the name of the function should be is_dataproc_version_at_least, since you're comparing a version number with that value.  Otherwise, I would expect it to compare two arguments as version numbers.

`[[ $(echo "$DATAPROC_VERSION >= $VERSION" | bc -l) -eq 1 ]]` is pretty cryptic.

Consider these utility functions I've defined in install_gpu_driver.sh:

```
# For version (or real number) comparison                                                                                                          
# if first argument is greater than or equal to, greater than, less than or equal to, or less than the second                                      
# ( version_ge 2.0 2.1 ) evaluates to false                                                                                                        
# ( version_ge 2.2 2.1 ) evaluates to true                                                                                                         
function version_ge() ( set +x ;  [ "$1" = "$(echo -e "$1\n$2" | sort -V | tail -n1)" ] ; )                                                        
function version_gt() ( set +x ;  [ "$1" = "$2" ] && return 1 || version_ge "$1" "$2" ; )                                                          
function version_le() ( set +x ;  [ "$1" = "$(echo -e "$1\n$2" | sort -V | head -n1)" ] ; )                                                        
function version_lt() ( set +x ;  [ "$1" = "$2" ] && return 1 || version_le "$1" "$2" ; )                                                          
```

The logic in the functions is difficult to follow, but their names and the documentation preceding them helps to clarify.

2025-02-07 05:31 UTC, prince-cs commented on custom_image_utils/args_parser.py
> +_VALID_OPTIONAL_COMPONENTS = ["HIVE_WEBHCAT", "ZEPPELIN", "TRINO", "RANGER", "SOLR", "FLINK", "DOCKER", "HUDI", "ICEBERG", "PIG"]
@IshaAg can help with the reasoning for this

2025-02-07 05:31 UTC, prince-cs commented on custom_image_utils/args_parser.py
> +def _validate_components(s):
let me rename it to optional_components

2025-02-07 05:34 UTC, prince-cs commented on custom_image_utils/args_parser.py
> +      help="""Optional Components to be installed with the image.
done

2025-02-07 05:35 UTC, prince-cs commented on custom_image_utils/shell_script_generator.py
> +    if self.args["dataproc_version"]:
I checked that scenario as well and it was able to get the dataproc image version and its value was stored in variable `dataproc_version`

2025-02-07 05:36 UTC, prince-cs commented on startup_script/run.sh
> +  if [[ $(echo "$DATAPROC_VERSION >= $VERSION" | bc -l) -eq 1 ]]; then
I am storing the value in `DATAPROC_VERSION` defined on line no 37

2025-02-07 05:39 UTC, prince-cs commented on startup_script/run.sh
> +  if is_version_at_least "2.3" && [[ -n "$USER_DATAPROC_COMPONENTS" ]]; then
Done

2025-02-07 05:41 UTC, prince-cs commented
> > _ No description provided. _
> 
> Can you please update the description to clearly state what the change will do?

Done

2025-02-07 06:01 UTC, IshaAg commented on custom_image_utils/args_parser.py
> +_VALID_OPTIONAL_COMPONENTS = ["HIVE_WEBHCAT", "ZEPPELIN", "TRINO", "RANGER", "SOLR", "FLINK", "DOCKER", "HUDI", "ICEBERG", "PIG"]
Jupyter is part of core image now

2025-02-07 22:14 UTC, cjac commented on custom_image_utils/shell_script_generator.py
> +    if self.args["dataproc_version"]:
thanks for checking!

2025-02-12 08:53 UTC, prince-cs reviewed
Addressed all the comments

2025-02-15 10:07 UTC, cjac commented on custom_image_utils/args_parser.py
> +def _validate_components(s):
I don't think that change happened.

2025-02-15 20:25 UTC, cjac commented on custom_image_utils/args_parser.py
> +def _validate_components(s):
it looks like this was from a previous version of the script.

2025-02-15 20:26 UTC, cjac approved these changes
I tested these changes thoroughly yesterday.  LGTM.

2025-02-15 20:26 UTC, merged